// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtkiyffwxsozmygcvpwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0a2l5ZmZ3eHNvem15Z2N2cHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODA4MjEsImV4cCI6MjA2Njg1NjgyMX0.q-2frHKaTaC43xnStQny5HYiaDR_Nfekk6m8o_uONBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});